In [77]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import array
import numpy as np

In [78]:
DALBUCS = pd.read_csv("DALBUCS090921 - Sheet3-2.csv")

look up how to add empty row every other

In [79]:
DALBUCS

    ID Position               Name     Cost Team     DK   ESPN
0    1       QB          Tom Brady  11200.0   TB  23.00  21.60
1    2      NaN                NaN      NaN  NaN    NaN    NaN
2    3       QB       Dak Prescott  10400.0  DAL  30.33  20.90
3    4      NaN                NaN      NaN  NaN    NaN    NaN
4    5       RB    Ezekiel Elliott   9600.0  DAL  15.65  14.50
5    6      NaN                NaN      NaN  NaN    NaN    NaN
6    7       WR         Mike Evans   9200.0   TB  15.35  15.00
7    8      NaN                NaN      NaN  NaN    NaN    NaN
8    9       WR       Chris Godwin   8600.0   TB  15.18  13.18
9   10      NaN                NaN      NaN  NaN    NaN    NaN
10  11       WR       Amari Cooper   8400.0  DAL  15.55  15.00
11  12      NaN                NaN      NaN  NaN    NaN    NaN
12  13       WR        CeeDee Lamb   8200.0  DAL  14.04  14.90
13  14      NaN                NaN      NaN  NaN    NaN    NaN
14  15       RB  Leonard Fournette   7000.0   TB  13.86   9.50
15  16      NaN                NaN      NaN  NaN    NaN    NaN
16  17       WR     Michael Gallup   6200.0  DAL  11.21  12.60
17  18      NaN                NaN      NaN  NaN    NaN    NaN
18  19       WR      Antonio Brown   5600.0   TB  13.67  11.50
19  20      NaN                NaN      NaN  NaN    NaN    NaN
20  21       TE     Rob Gronkowski   5400.0   TB   9.16   7.70
21  22      NaN                NaN      NaN  NaN    NaN    NaN
22  23       TE       Blake Jarwin   5200.0  DAL   2.20   7.30
23  24      NaN                NaN      NaN  NaN    NaN    NaN
24  25       RB    Ronald Jones II   5000.0   TB  12.60   8.60
25  26      NaN                NaN      NaN  NaN    NaN    NaN
26  27      DST         Buccaneers   4800.0   TB   7.60   5.30
27  28      NaN                NaN      NaN  NaN    NaN    NaN
28  29       TE     Dalton Schultz   4600.0  DAL   9.22   5.60
29  30      NaN                NaN      NaN  NaN    NaN    NaN
30  31       RB       Tony Pollard   4200.0  DAL   7.55   6.10
31  32      NaN                NaN      NaN  NaN    NaN    NaN
32  33        K        Ryan Succop   4000.0   TB   9.35   7.80
33  34      NaN                NaN      NaN  NaN    NaN    NaN
34  35        K      Greg Zuerlein   3600.0  DAL   9.56   7.60
35  36      NaN                NaN      NaN  NaN    NaN    NaN
36  37      DST            Cowboys   3000.0  DAL   4.88   3.20
37  38      NaN                NaN      NaN  NaN    NaN    NaN
38  39       TE      Cameron Brate   2600.0   TB   5.87   1.40
39  40      NaN                NaN      NaN  NaN    NaN    NaN
40  41       TE        O.J. Howard   2200.0   TB   9.40   5.00
41  42      NaN                NaN      NaN  NaN    NaN    NaN
42  43       RB    Giovani Bernard   2000.0   TB   9.94   5.00
43  44      NaN                NaN      NaN  NaN    NaN    NaN
44  45       WR      Scotty Miller   1600.0   TB   6.53   2.50
45  46      NaN                NaN      NaN  NaN    NaN    NaN

In [80]:
#DALBUCS['ID'] = DALBUCS['ID'].index.astype(str)

In [90]:
#DALBUCS.index = DALBUCS.index + 1
DALBUCS

    ID Position               Name     Cost Team     DK   ESPN
0    1       QB          Tom Brady  11200.0   TB  23.00  21.60
1    2      NaN                NaN      NaN  NaN    NaN    NaN
2    3       QB       Dak Prescott  10400.0  DAL  30.33  20.90
3    4      NaN                NaN      NaN  NaN    NaN    NaN
4    5       RB    Ezekiel Elliott   9600.0  DAL  15.65  14.50
5    6      NaN                NaN      NaN  NaN    NaN    NaN
6    7       WR         Mike Evans   9200.0   TB  15.35  15.00
7    8      NaN                NaN      NaN  NaN    NaN    NaN
8    9       WR       Chris Godwin   8600.0   TB  15.18  13.18
9   10      NaN                NaN      NaN  NaN    NaN    NaN
10  11       WR       Amari Cooper   8400.0  DAL  15.55  15.00
11  12      NaN                NaN      NaN  NaN    NaN    NaN
12  13       WR        CeeDee Lamb   8200.0  DAL  14.04  14.90
13  14      NaN                NaN      NaN  NaN    NaN    NaN
14  15       RB  Leonard Fournette   7000.0   TB  13.86   9.50
15  16      NaN                NaN      NaN  NaN    NaN    NaN
16  17       WR     Michael Gallup   6200.0  DAL  11.21  12.60
17  18      NaN                NaN      NaN  NaN    NaN    NaN
18  19       WR      Antonio Brown   5600.0   TB  13.67  11.50
19  20      NaN                NaN      NaN  NaN    NaN    NaN
20  21       TE     Rob Gronkowski   5400.0   TB   9.16   7.70
21  22      NaN                NaN      NaN  NaN    NaN    NaN
22  23       TE       Blake Jarwin   5200.0  DAL   2.20   7.30
23  24      NaN                NaN      NaN  NaN    NaN    NaN
24  25       RB    Ronald Jones II   5000.0   TB  12.60   8.60
25  26      NaN                NaN      NaN  NaN    NaN    NaN
26  27      DST         Buccaneers   4800.0   TB   7.60   5.30
27  28      NaN                NaN      NaN  NaN    NaN    NaN
28  29       TE     Dalton Schultz   4600.0  DAL   9.22   5.60
29  30      NaN                NaN      NaN  NaN    NaN    NaN
30  31       RB       Tony Pollard   4200.0  DAL   7.55   6.10
31  32      NaN                NaN      NaN  NaN    NaN    NaN
32  33        K        Ryan Succop   4000.0   TB   9.35   7.80
33  34      NaN                NaN      NaN  NaN    NaN    NaN
34  35        K      Greg Zuerlein   3600.0  DAL   9.56   7.60
35  36      NaN                NaN      NaN  NaN    NaN    NaN
36  37      DST            Cowboys   3000.0  DAL   4.88   3.20
37  38      NaN                NaN      NaN  NaN    NaN    NaN
38  39       TE      Cameron Brate   2600.0   TB   5.87   1.40
39  40      NaN                NaN      NaN  NaN    NaN    NaN
40  41       TE        O.J. Howard   2200.0   TB   9.40   5.00
41  42      NaN                NaN      NaN  NaN    NaN    NaN
42  43       RB    Giovani Bernard   2000.0   TB   9.94   5.00
43  44      NaN                NaN      NaN  NaN    NaN    NaN
44  45       WR      Scotty Miller   1600.0   TB   6.53   2.50
45  46      NaN                NaN      NaN  NaN    NaN    NaN

In [91]:
numbers=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46]
cycle=[]

for ID in DALBUCS.ID:
    a = 'x['+str(ID)+']'
    cycle.append(a)

#    lala.append(player_code)
#for i in numbers:

In [92]:
cycle

['x[1]',
 'x[2]',
 'x[3]',
 'x[4]',
 'x[5]',
 'x[6]',
 'x[7]',
 'x[8]',
 'x[9]',
 'x[10]',
 'x[11]',
 'x[12]',
 'x[13]',
 'x[14]',
 'x[15]',
 'x[16]',
 'x[17]',
 'x[18]',
 'x[19]',
 'x[20]',
 'x[21]',
 'x[22]',
 'x[23]',
 'x[24]',
 'x[25]',
 'x[26]',
 'x[27]',
 'x[28]',
 'x[29]',
 'x[30]',
 'x[31]',
 'x[32]',
 'x[33]',
 'x[34]',
 'x[35]',
 'x[36]',
 'x[37]',
 'x[38]',
 'x[39]',
 'x[40]',
 'x[41]',
 'x[42]',
 'x[43]',
 'x[44]',
 'x[45]',
 'x[46]']

In [93]:
#sentence = ['this', 'is', 'a', 'sentence']
' + '.join(cycle)

#ycle.join(' ')

'x[1] + x[2] + x[3] + x[4] + x[5] + x[6] + x[7] + x[8] + x[9] + x[10] + x[11] + x[12] + x[13] + x[14] + x[15] + x[16] + x[17] + x[18] + x[19] + x[20] + x[21] + x[22] + x[23] + x[24] + x[25] + x[26] + x[27] + x[28] + x[29] + x[30] + x[31] + x[32] + x[33] + x[34] + x[35] + x[36] + x[37] + x[38] + x[39] + x[40] + x[41] + x[42] + x[43] + x[44] + x[45] + x[46]'

In [94]:
#DALBUCS['Cost'] = DALBUCS['Cost'].index.astype(str)

In [95]:
Cost_list = DALBUCS["Cost"].tolist()

In [96]:
Cost_list

[11200.0,
 nan,
 10400.0,
 nan,
 9600.0,
 nan,
 9200.0,
 nan,
 8600.0,
 nan,
 8400.0,
 nan,
 8200.0,
 nan,
 7000.0,
 nan,
 6200.0,
 nan,
 5600.0,
 nan,
 5400.0,
 nan,
 5200.0,
 nan,
 5000.0,
 nan,
 4800.0,
 nan,
 4600.0,
 nan,
 4200.0,
 nan,
 4000.0,
 nan,
 3600.0,
 nan,
 3000.0,
 nan,
 2600.0,
 nan,
 2200.0,
 nan,
 2000.0,
 nan,
 1600.0,
 nan]

In [97]:
Proj_list = DALBUCS["ESPN"].tolist()

In [98]:
Proj_list

[21.6,
 nan,
 20.9,
 nan,
 14.5,
 nan,
 15.0,
 nan,
 13.18,
 nan,
 15.0,
 nan,
 14.9,
 nan,
 9.5,
 nan,
 12.6,
 nan,
 11.5,
 nan,
 7.7,
 nan,
 7.3,
 nan,
 8.6,
 nan,
 5.3,
 nan,
 5.6,
 nan,
 6.1,
 nan,
 7.8,
 nan,
 7.6,
 nan,
 3.2,
 nan,
 1.4,
 nan,
 5.0,
 nan,
 5.0,
 nan,
 2.5,
 nan]

In [100]:
zip_iterator = zip(cycle, Cost_list)

player_and_cost = dict(zip_iterator)
player_and_cost

{'x[1]': 11200.0,
 'x[2]': nan,
 'x[3]': 10400.0,
 'x[4]': nan,
 'x[5]': 9600.0,
 'x[6]': nan,
 'x[7]': 9200.0,
 'x[8]': nan,
 'x[9]': 8600.0,
 'x[10]': nan,
 'x[11]': 8400.0,
 'x[12]': nan,
 'x[13]': 8200.0,
 'x[14]': nan,
 'x[15]': 7000.0,
 'x[16]': nan,
 'x[17]': 6200.0,
 'x[18]': nan,
 'x[19]': 5600.0,
 'x[20]': nan,
 'x[21]': 5400.0,
 'x[22]': nan,
 'x[23]': 5200.0,
 'x[24]': nan,
 'x[25]': 5000.0,
 'x[26]': nan,
 'x[27]': 4800.0,
 'x[28]': nan,
 'x[29]': 4600.0,
 'x[30]': nan,
 'x[31]': 4200.0,
 'x[32]': nan,
 'x[33]': 4000.0,
 'x[34]': nan,
 'x[35]': 3600.0,
 'x[36]': nan,
 'x[37]': 3000.0,
 'x[38]': nan,
 'x[39]': 2600.0,
 'x[40]': nan,
 'x[41]': 2200.0,
 'x[42]': nan,
 'x[43]': 2000.0,
 'x[44]': nan,
 'x[45]': 1600.0,
 'x[46]': nan}

In [112]:
s = ""
for k, v in player_and_cost.items():
    print(k,'*' ,v, '+')

x[1] * 11200.0 +
x[2] * nan +
x[3] * 10400.0 +
x[4] * nan +
x[5] * 9600.0 +
x[6] * nan +
x[7] * 9200.0 +
x[8] * nan +
x[9] * 8600.0 +
x[10] * nan +
x[11] * 8400.0 +
x[12] * nan +
x[13] * 8200.0 +
x[14] * nan +
x[15] * 7000.0 +
x[16] * nan +
x[17] * 6200.0 +
x[18] * nan +
x[19] * 5600.0 +
x[20] * nan +
x[21] * 5400.0 +
x[22] * nan +
x[23] * 5200.0 +
x[24] * nan +
x[25] * 5000.0 +
x[26] * nan +
x[27] * 4800.0 +
x[28] * nan +
x[29] * 4600.0 +
x[30] * nan +
x[31] * 4200.0 +
x[32] * nan +
x[33] * 4000.0 +
x[34] * nan +
x[35] * 3600.0 +
x[36] * nan +
x[37] * 3000.0 +
x[38] * nan +
x[39] * 2600.0 +
x[40] * nan +
x[41] * 2200.0 +
x[42] * nan +
x[43] * 2000.0 +
x[44] * nan +
x[45] * 1600.0 +
x[46] * nan +

In [ ]:
playercode = zip(cycle, Player)

player_and_cost = dict(zip_iterator)
player_and_cost