In [168]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import array
import numpy as np

In [169]:
PlayerStats = pd.read_csv("LookingGood.csv")

In [170]:
PlayerStats

,Unnamed: 0,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitAssists,DoubleDigitRebounds,DoubleDigitSteals,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName
0,0,1,1,2020-12-23,21-095,MIA,@,ORL,L (-6),0.0,...,0,0,0,0,False,False,0.0,0,11.75,Precious Achiuwa
1,1,2,2,2020-12-25,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,0,0,0,False,False,0.0,0,19.25,Precious Achiuwa
2,2,3,3,2020-12-29,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,0,0,0,False,False,0.0,0,16.00,Precious Achiuwa
3,3,4,4,2020-12-30,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,0,0,0,False,False,0.0,0,6.75,Precious Achiuwa
4,4,5,5,2021-01-01,21-104,MIA,@,DAL,L (-10),0.0,...,0,0,0,0,False,False,0.0,0,18.50,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,2021-05-09,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,0,0,0,False,False,0.0,0,17.50,Ivica Zubac
18986,71,69,69,2021-05-11,24-054,LAC,@,TOR,W (+19),1.0,...,0,1,0,0,True,False,1.5,0,38.50,Ivica Zubac
18987,72,70,70,2021-05-13,24-056,LAC,@,CHO,W (+23),1.0,...,0,1,0,0,False,False,0.0,0,25.75,Ivica Zubac
18988,73,71,71,2021-05-14,24-057,LAC,@,HOU,L (-7),1.0,...,0,0,0,0,False,False,0.0,0,5.00,Ivica Zubac
18989,74,72,72,2021-05-16,24-059,LAC,@,OKC,L (-5),1.0,...,0,0,0,0,False,False,0.0,0,0.00,Ivica Zubac

In [171]:
PlayerSalaries = pd.read_csv("DK Salary Table.csv")
PlayerSalaries

       Unnamed: 0  DK Sal    Minutes        Date          First  Last
0               0  3200.0   2.866667  20210519.0         Drew Eubanks
1               1  3400.0   8.650000  20210516.0         Drew Eubanks
2               2  3100.0  22.966667  20210515.0         Drew Eubanks
3               3  3200.0  13.450000  20210513.0         Drew Eubanks
4               4  3200.0  13.666667  20210512.0         Drew Eubanks
...           ...     ...        ...         ...                  ...
37053       38759  3200.0  11.733333  20210103.0  Willie Cauley-Stein
37054       38760  3200.0  11.100000  20210101.0  Willie Cauley-Stein
37055       38761  3300.0   9.350000  20201230.0  Willie Cauley-Stein
37056       38763  3000.0  14.083333  20201225.0  Willie Cauley-Stein
37057       38764  3000.0   6.033333  20201223.0  Willie Cauley-Stein

[37058 rows x 5 columns]

In [172]:
PlayerStats

,Unnamed: 0,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitAssists,DoubleDigitRebounds,DoubleDigitSteals,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName
0,0,1,1,2020-12-23,21-095,MIA,@,ORL,L (-6),0.0,...,0,0,0,0,False,False,0.0,0,11.75,Precious Achiuwa
1,1,2,2,2020-12-25,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,0,0,0,False,False,0.0,0,19.25,Precious Achiuwa
2,2,3,3,2020-12-29,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,0,0,0,False,False,0.0,0,16.00,Precious Achiuwa
3,3,4,4,2020-12-30,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,0,0,0,False,False,0.0,0,6.75,Precious Achiuwa
4,4,5,5,2021-01-01,21-104,MIA,@,DAL,L (-10),0.0,...,0,0,0,0,False,False,0.0,0,18.50,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,2021-05-09,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,0,0,0,False,False,0.0,0,17.50,Ivica Zubac
18986,71,69,69,2021-05-11,24-054,LAC,@,TOR,W (+19),1.0,...,0,1,0,0,True,False,1.5,0,38.50,Ivica Zubac
18987,72,70,70,2021-05-13,24-056,LAC,@,CHO,W (+23),1.0,...,0,1,0,0,False,False,0.0,0,25.75,Ivica Zubac
18988,73,71,71,2021-05-14,24-057,LAC,@,HOU,L (-7),1.0,...,0,0,0,0,False,False,0.0,0,5.00,Ivica Zubac
18989,74,72,72,2021-05-16,24-059,LAC,@,OKC,L (-5),1.0,...,0,0,0,0,False,False,0.0,0,0.00,Ivica Zubac

In [173]:
PlayerStats['Date'] = PlayerStats['Date'].str.replace('-','')

In [174]:
PlayerStats

,Unnamed: 0,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitAssists,DoubleDigitRebounds,DoubleDigitSteals,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName
0,0,1,1,20201223,21-095,MIA,@,ORL,L (-6),0.0,...,0,0,0,0,False,False,0.0,0,11.75,Precious Achiuwa
1,1,2,2,20201225,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,0,0,0,False,False,0.0,0,19.25,Precious Achiuwa
2,2,3,3,20201229,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,0,0,0,False,False,0.0,0,16.00,Precious Achiuwa
3,3,4,4,20201230,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,0,0,0,False,False,0.0,0,6.75,Precious Achiuwa
4,4,5,5,20210101,21-104,MIA,@,DAL,L (-10),0.0,...,0,0,0,0,False,False,0.0,0,18.50,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,20210509,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,0,0,0,False,False,0.0,0,17.50,Ivica Zubac
18986,71,69,69,20210511,24-054,LAC,@,TOR,W (+19),1.0,...,0,1,0,0,True,False,1.5,0,38.50,Ivica Zubac
18987,72,70,70,20210513,24-056,LAC,@,CHO,W (+23),1.0,...,0,1,0,0,False,False,0.0,0,25.75,Ivica Zubac
18988,73,71,71,20210514,24-057,LAC,@,HOU,L (-7),1.0,...,0,0,0,0,False,False,0.0,0,5.00,Ivica Zubac
18989,74,72,72,20210516,24-059,LAC,@,OKC,L (-5),1.0,...,0,0,0,0,False,False,0.0,0,0.00,Ivica Zubac

In [175]:
#PlayerStats["Date"] = pd.to_numeric(PlayerStats["Date"], errors='coerce')

In [176]:
PlayerStats

,Unnamed: 0,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitAssists,DoubleDigitRebounds,DoubleDigitSteals,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName
0,0,1,1,20201223,21-095,MIA,@,ORL,L (-6),0.0,...,0,0,0,0,False,False,0.0,0,11.75,Precious Achiuwa
1,1,2,2,20201225,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,0,0,0,False,False,0.0,0,19.25,Precious Achiuwa
2,2,3,3,20201229,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,0,0,0,False,False,0.0,0,16.00,Precious Achiuwa
3,3,4,4,20201230,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,0,0,0,False,False,0.0,0,6.75,Precious Achiuwa
4,4,5,5,20210101,21-104,MIA,@,DAL,L (-10),0.0,...,0,0,0,0,False,False,0.0,0,18.50,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,20210509,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,0,0,0,False,False,0.0,0,17.50,Ivica Zubac
18986,71,69,69,20210511,24-054,LAC,@,TOR,W (+19),1.0,...,0,1,0,0,True,False,1.5,0,38.50,Ivica Zubac
18987,72,70,70,20210513,24-056,LAC,@,CHO,W (+23),1.0,...,0,1,0,0,False,False,0.0,0,25.75,Ivica Zubac
18988,73,71,71,20210514,24-057,LAC,@,HOU,L (-7),1.0,...,0,0,0,0,False,False,0.0,0,5.00,Ivica Zubac
18989,74,72,72,20210516,24-059,LAC,@,OKC,L (-5),1.0,...,0,0,0,0,False,False,0.0,0,0.00,Ivica Zubac

In [177]:
#PlayerSalaries["Date"] = pd.to_numeric(PlayerSalaries["Date"], errors='coerce')

In [178]:
PlayerSalaries

       Unnamed: 0  DK Sal    Minutes        Date          First  Last
0               0  3200.0   2.866667  20210519.0         Drew Eubanks
1               1  3400.0   8.650000  20210516.0         Drew Eubanks
2               2  3100.0  22.966667  20210515.0         Drew Eubanks
3               3  3200.0  13.450000  20210513.0         Drew Eubanks
4               4  3200.0  13.666667  20210512.0         Drew Eubanks
...           ...     ...        ...         ...                  ...
37053       38759  3200.0  11.733333  20210103.0  Willie Cauley-Stein
37054       38760  3200.0  11.100000  20210101.0  Willie Cauley-Stein
37055       38761  3300.0   9.350000  20201230.0  Willie Cauley-Stein
37056       38763  3000.0  14.083333  20201225.0  Willie Cauley-Stein
37057       38764  3000.0   6.033333  20201223.0  Willie Cauley-Stein

[37058 rows x 5 columns]

In [179]:
#PlayerSalaries["NewDate"]=PlayerSalaries['Date"]
PlayerStats["Date"] = pd.to_numeric(PlayerStats["Date"], downcast="float")
PlayerStats

,Unnamed: 0,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitAssists,DoubleDigitRebounds,DoubleDigitSteals,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName
0,0,1,1,20201224.0,21-095,MIA,@,ORL,L (-6),0.0,...,0,0,0,0,False,False,0.0,0,11.75,Precious Achiuwa
1,1,2,2,20201224.0,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,0,0,0,False,False,0.0,0,19.25,Precious Achiuwa
2,2,3,3,20201228.0,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,0,0,0,False,False,0.0,0,16.00,Precious Achiuwa
3,3,4,4,20201230.0,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,0,0,0,False,False,0.0,0,6.75,Precious Achiuwa
4,4,5,5,20210100.0,21-104,MIA,@,DAL,L (-10),0.0,...,0,0,0,0,False,False,0.0,0,18.50,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,20210508.0,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,0,0,0,False,False,0.0,0,17.50,Ivica Zubac
18986,71,69,69,20210512.0,24-054,LAC,@,TOR,W (+19),1.0,...,0,1,0,0,True,False,1.5,0,38.50,Ivica Zubac
18987,72,70,70,20210512.0,24-056,LAC,@,CHO,W (+23),1.0,...,0,1,0,0,False,False,0.0,0,25.75,Ivica Zubac
18988,73,71,71,20210514.0,24-057,LAC,@,HOU,L (-7),1.0,...,0,0,0,0,False,False,0.0,0,5.00,Ivica Zubac
18989,74,72,72,20210516.0,24-059,LAC,@,OKC,L (-5),1.0,...,0,0,0,0,False,False,0.0,0,0.00,Ivica Zubac

In [180]:
#PlayerSalaries['Date'] = PlayerSalaries["Date"].index.astype(str).str[4:8]
PlayerSalaries

       Unnamed: 0  DK Sal    Minutes        Date          First  Last
0               0  3200.0   2.866667  20210519.0         Drew Eubanks
1               1  3400.0   8.650000  20210516.0         Drew Eubanks
2               2  3100.0  22.966667  20210515.0         Drew Eubanks
3               3  3200.0  13.450000  20210513.0         Drew Eubanks
4               4  3200.0  13.666667  20210512.0         Drew Eubanks
...           ...     ...        ...         ...                  ...
37053       38759  3200.0  11.733333  20210103.0  Willie Cauley-Stein
37054       38760  3200.0  11.100000  20210101.0  Willie Cauley-Stein
37055       38761  3300.0   9.350000  20201230.0  Willie Cauley-Stein
37056       38763  3000.0  14.083333  20201225.0  Willie Cauley-Stein
37057       38764  3000.0   6.033333  20201223.0  Willie Cauley-Stein

[37058 rows x 5 columns]

In [181]:
PlayerSalaries["PlayerFullName"]=PlayerSalaries["First  Last"]

In [182]:
PlayerSalaries

,Unnamed: 0,DK Sal,Minutes,Date,First Last,PlayerFullName
0,0,3200.0,2.866667,20210519.0,Drew Eubanks,Drew Eubanks
1,1,3400.0,8.650000,20210516.0,Drew Eubanks,Drew Eubanks
2,2,3100.0,22.966667,20210515.0,Drew Eubanks,Drew Eubanks
3,3,3200.0,13.450000,20210513.0,Drew Eubanks,Drew Eubanks
4,4,3200.0,13.666667,20210512.0,Drew Eubanks,Drew Eubanks
...,...,...,...,...,...,...
37053,38759,3200.0,11.733333,20210103.0,Willie Cauley-Stein,Willie Cauley-Stein
37054,38760,3200.0,11.100000,20210101.0,Willie Cauley-Stein,Willie Cauley-Stein
37055,38761,3300.0,9.350000,20201230.0,Willie Cauley-Stein,Willie Cauley-Stein
37056,38763,3000.0,14.083333,20201225.0,Willie Cauley-Stein,Willie Cauley-Stein
37057,38764,3000.0,6.033333,20201223.0,Willie Cauley-Stein,Willie Cauley-Stein

In [191]:
#del PlayerSalaries["First  Last"]
PlayerSalaries["DK Sal"] = pd.to_numeric(PlayerSalaries["DK Sal"], downcast="float")

In [192]:
PlayerSalaries

       Unnamed: 0  DK Sal    Minutes        Date       PlayerFullName
0               0  3200.0   2.866667  20210519.0         Drew Eubanks
1               1  3400.0   8.650000  20210516.0         Drew Eubanks
2               2  3100.0  22.966667  20210515.0         Drew Eubanks
3               3  3200.0  13.450000  20210513.0         Drew Eubanks
4               4  3200.0  13.666667  20210512.0         Drew Eubanks
...           ...     ...        ...         ...                  ...
37053       38759  3200.0  11.733333  20210103.0  Willie Cauley-Stein
37054       38760  3200.0  11.100000  20210101.0  Willie Cauley-Stein
37055       38761  3300.0   9.350000  20201230.0  Willie Cauley-Stein
37056       38763  3000.0  14.083333  20201225.0  Willie Cauley-Stein
37057       38764  3000.0   6.033333  20201223.0  Willie Cauley-Stein

[37058 rows x 5 columns]

In [193]:
PlayerSalaries["PlayerFullName"] = PlayerSalaries["PlayerFullName"].astype(str)
PlayerSalaries

       Unnamed: 0  DK Sal    Minutes        Date       PlayerFullName
0               0  3200.0   2.866667  20210519.0         Drew Eubanks
1               1  3400.0   8.650000  20210516.0         Drew Eubanks
2               2  3100.0  22.966667  20210515.0         Drew Eubanks
3               3  3200.0  13.450000  20210513.0         Drew Eubanks
4               4  3200.0  13.666667  20210512.0         Drew Eubanks
...           ...     ...        ...         ...                  ...
37053       38759  3200.0  11.733333  20210103.0  Willie Cauley-Stein
37054       38760  3200.0  11.100000  20210101.0  Willie Cauley-Stein
37055       38761  3300.0   9.350000  20201230.0  Willie Cauley-Stein
37056       38763  3000.0  14.083333  20201225.0  Willie Cauley-Stein
37057       38764  3000.0   6.033333  20201223.0  Willie Cauley-Stein

[37058 rows x 5 columns]

In [194]:
PlayerStats["PlayerFullName"] = PlayerStats["PlayerFullName"].astype(str)
PlayerStats

,Unnamed: 0,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitAssists,DoubleDigitRebounds,DoubleDigitSteals,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName
0,0,1,1,20201224.0,21-095,MIA,@,ORL,L (-6),0.0,...,0,0,0,0,False,False,0.0,0,11.75,Precious Achiuwa
1,1,2,2,20201224.0,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,0,0,0,False,False,0.0,0,19.25,Precious Achiuwa
2,2,3,3,20201228.0,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,0,0,0,False,False,0.0,0,16.00,Precious Achiuwa
3,3,4,4,20201230.0,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,0,0,0,False,False,0.0,0,6.75,Precious Achiuwa
4,4,5,5,20210100.0,21-104,MIA,@,DAL,L (-10),0.0,...,0,0,0,0,False,False,0.0,0,18.50,Precious Achiuwa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,20210508.0,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,0,0,0,False,False,0.0,0,17.50,Ivica Zubac
18986,71,69,69,20210512.0,24-054,LAC,@,TOR,W (+19),1.0,...,0,1,0,0,True,False,1.5,0,38.50,Ivica Zubac
18987,72,70,70,20210512.0,24-056,LAC,@,CHO,W (+23),1.0,...,0,1,0,0,False,False,0.0,0,25.75,Ivica Zubac
18988,73,71,71,20210514.0,24-057,LAC,@,HOU,L (-7),1.0,...,0,0,0,0,False,False,0.0,0,5.00,Ivica Zubac
18989,74,72,72,20210516.0,24-059,LAC,@,OKC,L (-5),1.0,...,0,0,0,0,False,False,0.0,0,0.00,Ivica Zubac

In [195]:
#Blended=pd.merge(PlayerStats, PlayerSalaries, on=["PlayerFullName","Date"])

In [196]:
#Blended

In [197]:
new_df = pd.merge(PlayerStats, PlayerSalaries,  how='left', left_on=['Date','PlayerFullName'], right_on = ['Date','PlayerFullName'])

In [198]:
new_df

,Unnamed: 0_x,Rk,G,Date,Age,Tm,Unnamed: 5,Opp,Unnamed: 7,GS,...,DoubleDigitBlocks,DoubleDouble,TripleDouble,DDPoints,TDPoints,DraftKingTotals,PlayerFullName,Unnamed: 0_y,DK Sal,Minutes
0,0,1,1,20201224.0,21-095,MIA,@,ORL,L (-6),0.0,...,0,False,False,0.0,0,11.75,Precious Achiuwa,NaN,NaN,NaN
1,1,2,2,20201224.0,21-097,MIA,NaN,NOP,W (+13),0.0,...,0,False,False,0.0,0,19.25,Precious Achiuwa,NaN,NaN,NaN
2,2,3,3,20201228.0,21-101,MIA,NaN,MIL,L (-47),0.0,...,0,False,False,0.0,0,16.00,Precious Achiuwa,NaN,NaN,NaN
3,3,4,4,20201230.0,21-102,MIA,NaN,MIL,W (+11),0.0,...,0,False,False,0.0,0,6.75,Precious Achiuwa,NaN,NaN,NaN
4,4,5,5,20210100.0,21-104,MIA,@,DAL,L (-10),0.0,...,0,False,False,0.0,0,18.50,Precious Achiuwa,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18985,70,68,68,20210508.0,24-052,LAC,NaN,NYK,L (-6),1.0,...,0,False,False,0.0,0,17.50,Ivica Zubac,NaN,NaN,NaN
18986,71,69,69,20210512.0,24-054,LAC,@,TOR,W (+19),1.0,...,0,True,False,1.5,0,38.50,Ivica Zubac,NaN,NaN,NaN
18987,72,70,70,20210512.0,24-056,LAC,@,CHO,W (+23),1.0,...,0,False,False,0.0,0,25.75,Ivica Zubac,NaN,NaN,NaN
18988,73,71,71,20210514.0,24-057,LAC,@,HOU,L (-7),1.0,...,0,False,False,0.0,0,5.00,Ivica Zubac,NaN,NaN,NaN
18989,74,72,72,20210516.0,24-059,LAC,@,OKC,L (-5),1.0,...,0,False,False,0.0,0,0.00,Ivica Zubac,NaN,NaN,NaN

In [134]:
#Blended.iloc[2]['PlayerFullName_x']

'Precious Achiuwa '

In [135]:
#Blended.iloc[2]['PlayerFullName_y']

'Kyrie Irving'